[package]
name = "lilap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
rand = "0.8.5"
confee = "0.1.2"
signal-hook = "0.3"
once_cell = "1.17.0"